### ISSUE TITLE
installed but some trouble on after installation.

### ISSUE THREAD

**Issue by fraorlando90** [yllwfsh/Xiaomi-Notebook-Air-13.3-2018-macOS-EFI#3]
hi anyone, I', quiet new on hackintosh, I also have this fantastic xiaomi 2018, and I wnat to run mac os so bad on it...
M only problem is the after installation, I have o idea how to modify the kerne and how to upgrade the kext.
Would you please raccomand a good tutorial or just try to explain that? what shell I do exactly after installation?
I was also reading a kind of similar problem from a different discussion, looks like there is a new efi folder so I wont need to do anything else postinstall? if yes I would definitely reinstall the system and should be fixed... the discussion was open on this forum and the folder in question can be cached in here https://github.com/johnnync13/Xiaomi-Mi-Air", " this was the lik I found and it doesn't work anymore, so I post the Issues page and you can know better what I am talking about.
Thanks for all the job you guys make in here

**Comment by cnmoxie** [comment]
https://github.com/johnnync13/Xiaomi-Mi-Air",it work good once,but it doesn't work after he upgrade the efi files.

**Comment by yllwfsh** [comment]
Hi @fraorlando90 & @cnmoxie , If you've followed https://github.com/yllwfsh/Xiaomi-Notebook-Air-13.3-2018-macOS-EFI/blob/master/README.md you don't need to modify the kernel or update any kexts. My EFI folder should work for you, I don't know about johnnync13's EFI folder upgrade

**Comment by fraorlando90** [comment]
Thanks for your answers, sorry for my delay but with work I can’t stay on
my pc! I’ll try your folder, and see if everything works fine, I’ll let you
know that....
Please save my email address, fraorlando90@gmail.com

Il giorno dom 16 giu 2019 alle 18:46 yllwfsh <notifications@github.com> ha
scritto:
