### ISSUE TITLE
battery drain

### ISSUE THREAD

**Issue by fraorlando90** [yllwfsh/Xiaomi-Notebook-Air-13.3-2018-macOS-EFI#4]
hi anyone, trying this folder has been a great experience, everything works greatly and only the battery gets some problem: drains real quick, gets worm very fast and again very very worm! to reach the same temperature on windows I have to run raimbow six for 20 minutes, on mac only takes a few minues with a few open tabs with chrome...
I tried to figure out why it was doing that but obviusly I could not find a solution, I also changed the thermal paste, tried some new text but nothing again.
I had the chance to talk to someone has the previus model of xiaomi and high sierra on it, he says battery actually last longer than windows can do and temperature are even colder than running on windows instead.
I just tried to be detailed as much as I can and I hope somebody here can help us with this. Love this system and all the feature it has, let's fix only this

**Comment by fraorlando90** [comment]
me again guys, I found this guide that helps to keep the voltage down but I don't think I am expert enough to into it, I never used a compiler before.
Hope somebody knows more then me and help, this apparently the battery lifes improves a lot.
https://github.com/sicreative/VoltageShift

**Comment by yllwfsh** [comment]
Thanks for waiting till I had time to address this issue. To be honest I'm not comfortable touching CPU voltage hacks for macOS, but I have updated the UEFI drivers and Kexts to reduce the power usage slightly, let me know if it's better now. Find the commit here: https://github.com/yllwfsh/Xiaomi-Notebook-Air-13.3-2018-macOS-EFI/commit/0d3651aa70f995c26a206d57994b10b9d877c787 .

To install: Replace the drivers64UEFI and kexts folders in CLOVER.

**Comment by fraorlando90** [comment]
This is awesome, I’ll try and let you know!

Il giorno mer 7 ago 2019 alle 13:42 yllwfsh <notifications@github.com> ha
scritto:

**Comment by yllwfsh** [comment]
I hope it works! If your laptop still gets hot and has reduced battery life, please check that you don't have some processes running in the background that are using the CPU a lot (you can use Activity Monitor for that). Normal idle CPU usage should be 0-5%. If there's anything that's using more, try to quit the app or in the worst case try installing macOS from scratch and test battery life / heat then.

![image](https://user-images.githubusercontent.com/43885719/62630571-7b9d0400-b92f-11e9-8415-9a9d9e14c680.png)

**Comment by fraorlando90** [comment]
Thankyou very much, can’t wait to work and test it! Your help is needed

Il giorno mer 7 ago 2019 alle 16:22 yllwfsh <notifications@github.com> ha
scritto:

**Comment by fraorlando90** [comment]
hi, here I'm again, sorry for the delay but in august I work so much...
I find myself with another problem now, so I start from the begin and try
to explain better as I can.
I use mac os randomly because it's not super stable and because of the
power drain really, is the only thing it's annoying for me and how I use
it, but of course to make all the upgrades on the EFI and all the rest you
listed I had to go back and work by clover configurator of course, here is
my problem, clover does't show up in application file anymore, tried to
reinstall it but nothing , doesn't work at all, after a few days was trying
to reboot on mac and now it frozen as soon as I give the password at the
first page after boot.
I want to try to reinstall mac os and I was wonder if the efi folder is
already upgraded with the latest fix you posted or if I have to upgrade
after install, another thing is if you know what happened to my system...?
I really have no idea how and why clover wont show up again. HELP one more
time


Il giorno mer 7 ago 2019 alle ore 16:22 yllwfsh <notifications@github.com>
ha scritto:

**Comment by fraorlando90** [comment]
Hi again, I write with some result this time, you know with holidays and such I didn’t really find a lot of time to write.
So I had to reinstall the system than, and with your fix looks like it’s a way better then it used to be, I’m still in a testing situation, but I have to say so far I didn’t have any noise of heat and battery drain, still I’m testing the system only from a couple of days so I want to write back one I got more info and more testing days…finally doesn’t suck 1 per cent per minute! 
Thanks for your help, if there is anything I can do or test appositely to improve your folder you only have to ask.

**Comment by fraorlando90** [comment]
Hi again, after a little time to test the system I can affirm that your fix is working really well, It’s still a little less battery life than windows deliver but is really good anyway! Heat and battery are definitely comparable finally!
The only wrong I experience is the trackpad sometimes just completely stop working for no reason! And I found my self many time to restart the system. 
Another thing could work better is the audio from speakers, is very low and miss a lot of the quality that window gives instead, I know many people have trouble with earphones , but I honestly didn’t and I’ m actually using a nice AKG earphones they came out with my old galaxy and they just work well as window does.
Thanks for all the work you done, I will keep testing and give you reports if needed

**Comment by Ormsher** [comment]
Hi. To fix shitty track pad i suggest for you to clean your kext cache and see if that fixes it.
`sudo chmod -R 755 /System/Library/Extensions/
sudo chown -R root:wheel /System/Library/Extensions/
sudo chmod -R 755 /Library/Extensions/
sudo chown -R root:wheel /Library/Extensions/
sudo touch /System/Library/Extensions/
sudo touch /Library/Extensions/
sudo kextcache -i / && sudo kextcache -u /`
