### ISSUE TITLE
Anyone tested on Catalina?

### ISSUE THREAD

**Issue by wilsonnkwan** [yllwfsh/Xiaomi-Notebook-Air-13.3-2018-macOS-EFI#5]
See Title. haha

**Comment by yllwfsh** [comment]
Haven't tested yet. For stability I'm staying on Mojave for now (Catalina is 64-bit only). I expect Clover will need an update to work with Catalina, otherwise drivers should be okay.

**Comment by yllwfsh** [comment]
As my hackintosh project is now retired, please have a look at https://github.com/johnnync13/Xiaomi-Mi-Air . I'm continuing to work on the Xiaomi Notebook Air there :)
