### ISSUE TITLE
LAN port

### ISSUE THREAD

**Issue by fraorlando90** [yllwfsh/Xiaomi-Notebook-Air-13.3-2018-macOS-EFI#6]
Hi there, having trouble on using my usb type c hub, it has a lan connector but not working! System says it’s connected with a yellow dat! 
Any help?

**Comment by yllwfsh** [comment]
@fraorlando90 Does your hub and the LAN port work on a real mac? Some USB type C hubs require specific LAN drivers in macOS. Try to find out under Linux or Windows what kind of chip it has and there might be some drivers available online.

**Comment by yllwfsh** [comment]
As my hackintosh project is now retired, please have a look at https://github.com/johnnync13/Xiaomi-Mi-Air . I'm continuing to work on the Xiaomi Notebook Air there :)
