### ISSUE TITLE
Constant reboot during install

### ISSUE THREAD

**Issue by benmod** [yllwfsh/Xiaomi-Notebook-Air-13.3-2018-macOS-EFI#7]
Hello, 

I am having an issue with a freshly bought Xiaomi Notebook Air 13.3 (i5 8250). I can boot into the install disk, then format the drive in APFS and start the installation, but about midway through the installation process the laptop just crashes and restart. 

Any idea what might be happening?

**Comment by yllwfsh** [comment]
Hi! What operating system are you trying to install? Mojave 10.14 or Catalina 10.15?

**Comment by benmod** [comment]
Mojave 10.14 freshly downloaded from my mac.

**Comment by benmod** [comment]
I tried with Clover 5071 and Clover 4945 and I have the same issue in both cases.

**Comment by yllwfsh** [comment]
Try removing any kexts **other than** the following from the installer USB CLOVER/kexts/Other folder (these are the minimum):

- CPUFriend (both)
- Lilu
- WhateverGreen
- NullEthernet
- SATA-unsupported
- USBPorts
- VirtualSMC
- Voodoo (all)

**Comment by benmod** [comment]
I have tried and the same problem happened. I am using a USB 3.0 drive for the installation, could that be the issue?

**Comment by benmod** [comment]
I tried installing directly on a USB stick rather than the internal SSD because I read there might be support issues with it. But same issue.

**Comment by lavjamanxd** [comment]
@benmod Do you have the original SSD installed in the machine?
It's a Samsung PM981 NVME SDD. Hackintosh is not compatible with that, i had 2 machines with that SSD and i was getting constant reboots while installing.
I replaced that SSD with an ADATA XPG SX8200 Pro which is compatible.

**Comment by yllwfsh** [comment]
> @benmod Do you have the original SSD installed in the machine?
> It's a Samsung PM981 NVME SDD. Hackintosh is not compatible with that, i had 2 machines (this xiaomi notebook and a HP elitedesk g3 sff) which came with that SSD and i was getting constant reboots while installing.
> I replaced that SSD with an ADATA XPG SX8200 Pro which is compatible.

I have a PM961 NVMe SSD in my 2018 Laptop, and that is supported, but I guess it's possible that there are versions going around with a different Samsung OEM SSD in them. @benmod You could indeed try to install to another SSD. Currently I have a WD Blue M.2 SATA SSD with a second macOS install, that one should work as well with the current EFI folder on here.

Alternatively you could try updating Clover on the installation USB after copying this EFI folder onto it and see if that makes a difference.

When I have some time soon I'll try to update the EFI folder Clover version and Kexts and publish an update here on Github.
